### ISSUE TITLE
[BUG] AI tag twice in equipement tag list

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1043]
<strong>Submitted At: </strong>9/4/2020 1:43:39
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
the IA tags appears twice in both lists
<strong>To Reproduce: </strong>
compendium-->equipment tag-->IA appears twice
<strong>Expected behavior: </strong>
having the tag appear only once
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by SapphicFire** [comment]
I decided to look into this because I'm hoping to get involved in working on this app (SapphicFire in Discord) - hope this is ok

All [lancer-data tags.json](https://github.com/massif-press/lancer-data/blob/master/lib/tags.json) values are being reflected on the Equipment Tag page excluding those where:
`"hidden": true`
is included in the object. As there are two objects with the name value of "AI" and neither of these are hidden, they are both displayed.

As "tg_bonus_ai" and "tg_ai" have identical names and descriptions, the user cannot differentiate the use of these tags. 

Depending on intention here options could be to apply hidden (doesn't seem appropriate) or provide some distinction in text (description) and/or title(name). The Name value will be the big thing in appeasing users thinking this is a duplicate, I feel.

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
