### ISSUE TITLE
[BUG] Overkill Additive on Segment Knife

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1143]
<strong>Submitted At: </strong>1/4/2021 3:37:42
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
Segment Knife's damage roll generating excess damage; for instance, damage collecting up to exceed maximum possible of 4 and accumulate to 5, 6, 7. Possible that the +1 is getting accumulated due to Overkill rerolls; but unsure as math seems to cut short.
<strong>To Reproduce: </strong>
Equip Mech with Segment Knife.
Enter Active Mode.
Either Barrage or Skirmish, and select Segment Knife.
Roll to hit for Segment Knife, confirm as hit, then roll damage.

<strong>Expected behavior: </strong>
Given Segment Knife's damage roll of 1d3+1,  expected damage range available should just be 3-4, given 2 (implicit roll of 1, +1) should trigger Overkill; and no matter number of Overkills, end result's damage should only ever be 4 at most.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by Sanagi575** [comment]
![image](https://user-images.githubusercontent.com/52812372/108017434-7d429000-6fda-11eb-9e30-e78b74fa9d86.png)
Possible adjusted theory: The Total Damage readout is truly, simply adding up all dice rolls made, including rerolls, and displaying that sum as the total; this seems to hold across multiple examples, such as the above (4 rolls of 1, + 1 roll of 2, displaying as total damage of 6), or a 1 and then a 3 being displayed as 4, 1 and 1 and 2 = 4, etc.

As well, it seems to reveal that the Segment Knife (and possibly other weapons with the Overkill tag) assumes that there will always be at least one Overkill reroll at all times, and that the damage calculation math works off of this instead of the xdx+x formulae displayed for most weaponry.
