### ISSUE TITLE
[BUG] Siege Cannon not Loading

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1423]
<strong>Submitted At: </strong>5/9/2021 22:28:18
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Siege Cannon on Siege mode does not have the loading button after fired. Still able to barrage even after firing in Siege mode in previous turn.
<strong>To Reproduce: </strong>
Gain three licenses in Barbarossa. Enter Active Mode. Barrage Siege Cannon while in Siege mode. End Turn, Next Turn
<strong>Expected behavior: </strong>
After Barraging Siege Cannon while in Siege Mode, the Siege cannon should be locked out from using until it is loaded again
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by TranslucentSabre** [comment]
This is not the only profile-granted tag affected, probably because the tags granted by weapon profiles that actually affect comp/con active mode are few. "Reliable 5" from the "Spin-Up Mode" profile of "LEVIATHAN HEAVY ASSAULT CANNON" is also not applied correctly, however "Heat 2 ( Self )" from the same weapon/profile is applied when firing.
