### ISSUE TITLE
[BUG] Lich image empty

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1439]
<strong>Submitted At: </strong>5/24/2021 14:45:09
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
I went to check out images for the Lich frame. When I clicked on the original image it now displays as empty/non existing image/broken image. It also doesn't display on mech hangar.
<strong>To Reproduce: </strong>
Make a lich frame. Click to change image, click on original image then set image.
<strong>Expected behavior: </strong>
Original image is displayed.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
DarkMayhem#4060
<strong>Stack Trace: </strong>
Empty

**Comment by msprijatelj** [comment]
This issue seems to stem from a mismatch of filenames between the static hosted images in COMP/CON and the provided image URLs in the [Long Rim frame data](https://github.com/massif-press/long-rim-data/blob/master/frames.json).  I haven't delved too deep yet, but I'm guessing the file path to the image is being directly applied to the `static/img/mech/` directory when reselecting the base image, instead of pointing at the AWS hosted image.  Without access to the AWS bucket, the quickest solution would be to rename all the COMP/CON static images to match the AWS filenames (e.g. rename COMP/CON's `mf_lich.png` to `lich_off.png`).  I'll dig in and see if there's a different approach that will add resiliency.
