### ISSUE TITLE
[BUG] Failing to cache color scheme

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1450]
<strong>Submitted At: </strong>6/2/2021 16:07:16
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
COMP/CON doesn't cache what color scheme you have selected long term when signed into a COMP/CON account. It may do this when not signed in as well, but I haven't tested it.
<strong>To Reproduce: </strong>
Sign into COMP/CON. Select a color scheme for the site. Close the site and reopen it twice. See bug.
<strong>Expected behavior: </strong>
The color scheme to be remembered.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by msprijatelj** [comment]
Looked into this: I believe the issue is that the app doesn't sync immediately after the user changes their theme.  My workaround was:
1. Log into cloud account
2. Change theme
3. Trigger Manual Sync
4. Refresh repeatedly; cloud sync theme is retained properly
Looking into adding a sync toggle on Theme change
