### ISSUE TITLE
[BUG] No check marks for community content

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1460]
<strong>Submitted At: </strong>6/7/2021 11:12:05
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The green "installed" check mark does not appear next to the version number for "Field guide to castor and pollux" and "Waffenfabrik Zalewski" in the LCP directory despite both being installed
<strong>To Reproduce: </strong>
Simply download either or both aforementioned community content packs, and go to the LCP directory, both do not have a green checkmark indicating that they are downloaded and up to date
<strong>Expected behavior: </strong>
Expected a green checkmark indicating they are downloaded to appear next to the version number
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by TranslucentSabre** [comment]
@jarena3 I've looked into this one and I don't believe this is something that can be fixed by PR. Comp/Con only lists an LCP file as installed if the "name" filed in the .lcp file matches the "name" or "title" field of the lcp listing on AWS.

This is correct, but the values are not correct for "Field Guide to Castor and Pollux" or "Waffenfabrik Zalewski" as seen here.

The name in the .lcp as displayed via the "CONTENT PACKS" dialog:
![image](https://user-images.githubusercontent.com/6234658/121250762-bb0a4380-c86b-11eb-92cc-f3f7988a77ed.png)

The name and title data found in communitypacks.json:
![image](https://user-images.githubusercontent.com/6234658/121250882-db3a0280-c86b-11eb-8f77-8a969432cdaf.png)
![image](https://user-images.githubusercontent.com/6234658/121250921-e5f49780-c86b-11eb-85a3-5b87b840e1ea.png)


These values look like they will either need to be fixed in communitypacks.json, or my the producer of the .lcp files during LCP generation. I, personally, would opt to update the "title" field in communitypacks.json but do not know the procedure for that.

**Comment by TranslucentSabre** [comment]
This same issue is also present for "Field Guide to Mfecane" which displays a name of "Mfecane Field Guide" when installed.
![image](https://user-images.githubusercontent.com/6234658/121251513-92cf1480-c86c-11eb-8c20-c2f02f24eac6.png)

**Comment by TranslucentSabre** [comment]
@jarena3 , I do not believe this has been fixed. Has the aws hosted communitypacks.json been updated? It does not appear to be.
