### ISSUE TITLE
[BUG] Empath Rank I Missing 1/round tag

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1555]
<strong>Submitted At: </strong> 7/29/2021 0:09:43<br><br><strong>Source: </strong> No Room for a Wallflower<br><br><strong>Incorrect Text/Data: </strong><br> When viewed in the compendium, tactical profile, or active mode, Empath 1 is missing the 1/scene tag. This appears to be a rendering issue, as it has a frequency: 1/scene tag in the code of the lcp, it just doesn't show up in comp/con.<br><br><strong>Correct Text/Data: </strong><br> It may be best to just add 1/scene in the descriptive text, outside of the reaction text box itself for now, such as "1/scene, your ability to sense the subjectivities of others..."<br>

**Comment by msprijatelj** [comment]
Looked into this: I noticed that other Talents lack a 1/round or 1/scene tag, even if they don't include them in their descriptive text (saw this with Gunslinger II: Return Fire, which is a 1/round reaction).  This may be a broader rendering issue, for sure.

Besides that, I tested the Empath I: Sympathetic Precognition talent in Active Mode, and found that it refreshed on a new round instead of staying deactivated for the rest of the scene.  I'll open up a separate issue for that.
