### ISSUE TITLE
[BUG] skill reserve giving 2 skill points

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1589]
<strong>Submitted At: </strong>8/3/2021 20:32:08
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
the skill point reserve is supposed give one +2 skill bonus. it is currently giving two
<strong>To Reproduce: </strong>
just add the reserve
<strong>Expected behavior: </strong>
skill point  gives one +2 skill bonus.
<strong>Additional context: </strong>
 version  2.2.28 
<strong>Contact Info: </strong>
Tamaris_Mora_S27#1022 (discord)
<strong>Stack Trace: </strong>

**Comment by msprijatelj** [comment]
Looked into this: In the [bonus_dictionary.json](https://github.com/massif-press/compcon/blob/master/src/assets/bonus_dictionary.json) and `getMaxSkillPoints` function in Pilot.ts, if I change `skill_points` to `skill_trigger_points` to avoid a potential match with `mech_skill_points`, I see the intended behavior of 1 skill point added per "Skill Point" reserve.  I'm guessing COMP/CON is using "string contains" instead of "string matches" somewhere in the Bonus class, leading to 2 entries in bonuses and thus 2 points added.

**Comment by msprijatelj** [comment]
@jarena3 We may need to revert #1564 while I work on a more in-depth fix.

Otherwise, workaround for current state is:
1. Go to Active Mode
2. Open Downtime
3. Select "Get Focused"; click "Improve Skill"
4. Single skill point will be added.

**Comment by msprijatelj** [comment]
More info on the depth: Right now, we have essentially "custom" reserves being created during the Downtime activities (i.e. reserves that aren't in the `lancer-data` repo).  Problem is, we don't serialize/deserialize Bonuses, Actions, and Synergies when serializing/deserializing Reserves.  I believe we may want to introduce Serializers/Deserializers for these classes so that they are saved properly for other custom reserves?

I'd normally say "throw these reserves into `lancer-data` and build around them", but the actual, homebrewed "Custom Reserve" reserve could probably benefit from this Serialization/Deserialization.
