### ISSUE TITLE
[BUG] Slag Cannon Erroneous Tag

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1635]
<strong>Submitted At: </strong> 8/21/2021 12:30:00<br><br><strong>Source: </strong> The Long Rim<br><br><strong>Incorrect Text/Data: </strong><br> The Slag Cannon erroneously has the Deployable tag and the Free Action tag, when the Slag object that it creates shouldn't technically be a Deployable for rules interaction purposes, and the weapon itself shouldn't have the Free Action tag or the Deployable tag.<br><br><strong>Correct Text/Data: </strong><br> This may be because of Active Mode limitations, but the Slag object shouldn't be tagged with Deployable, and the weapon should only have the Heat 1 (Self) tag. The Free Action tag is also erroneous here, which has rules implications as you could usually use the Slag Cannon's Slag effect during situations where you aren't allowed to take Free Actions. <br>

**Comment by msprijatelj** [comment]
@jarena3 This is a weird case where it feels like some of the Kobold's traits/equipment should be errata'd with the Deployable tag (though I don't know how best to put that on a Frame trait or Core Power). Do you have any suggestions on how to address this case?

**Comment by jarena3** [comment]
yeah, it's a weird case wherein C/C is trying to render special rules. My sort of go-to answer is that one has to follow the rules as written (in the book) rather than getting everything from C/C, that C/C is a tool trying to translate book rules into an app and can't really be the final word.
That said, I know a lot of users exclusively (or nearly so) look at C/C, especially when it comes to compendium stuff.

I do agree that the Deployable tag makes sense here as errata. As for the rest... I don't know. I understand what the ticket is getting at but also I don't know if it's worth the effort in making these changes. I feel like we can kind of leave this one be, especially because I think if this comes up in the context of a game there's going to be a far greater impetus to check C/C's interpretation against the actual rules document.

Going to close this (then get yelled at later for it, probably)
