### ISSUE TITLE
[FEATURE] Quickstart Higher-Level Character Creator

### ISSUE THREAD

**Issue by ehildebrand** [massif-press/compcon#1687]
**Is your feature request related to a problem? Please describe.**
I enjoy building higher-level theoretical character builds with everyone on the mech-hangar channel on discord. However, it can be frustrating to create several higher-level characters since for each character I have to:

- Fill in a character name & Callsign
- Select a template to skip through character creation quickly
- Undo all the options from the template
- Manually set the license level to the desired level

**Describe the solution you'd like**
I'd like an option to immediately create a character at a higher level (for example, LL6) instead of manually having to set that after character creation, and also skip details such as mech skills and talents so I can fill them in later when I feel like it.

**Alternatives**
If it'd be easier to implement it would already help a lot to be able to just select a "blank" character template (aka with no mech skills, talents, etc. assigned yet).

**Additional context**
None

**Comment by msprijatelj** [comment]
I like the idea of adding a "skip character wizard" button a lot more than a blank template, as the purpose of the templates are for new players to have prebuilt options ready to go.  Adding a blank template would probably lead to confusion, while the intent of a "skip" button would be fairly clear.  We could probably keep the "register new pilot" button active and assign placeholder information for names/callsigns if left empty, and just move the warnings to be above the "Register" button.

**Comment by msprijatelj** [comment]
I checked whether the pilot callsign or name could be empty without breaking pilot management.  Some notes:

- I was able to "delete" the pilot's name and callsign as long as I replaced the old name/callsign with whitespace chracters (e.g. ` `).  Apparently the new name is verified first, THEN the whitespace is stripped.  Relevant if we want to actually prevent non-empty names & callsigns.
- While logged in, when working in pilot management, pilot roster, Active Mode, Mission Runner, and syncing, no breaking errors occurred with empty names/callsigns.  The only error I encountered occurred when trying to edit an empty Pilot Name, and that error was simply `this.$slots.default is undefined`- basically telling me the pilot name was empty but otherwise not obstructing my work.
