### ISSUE TITLE
[BUG] Centimane synergy

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1733]
<strong>Submitted At: </strong> 10/19/2021 3:13:32<br><br><strong>Issue: </strong><br> When a pilot has Centimane III, in the mech sheet it shows a synergy diamond for both Ten Thousand Teeth and Tidal Suppression. With Tidal Suppression explicitly stating that it replaces Ten Thousand Teeth, shouldn't it only have the one diamond?
This may be more of a cosmetic/visual issue than anything, but noticed it while paging through some character sheets I have.<br><br><strong>Massif Reference: </strong> Lancer CRB page 92<br>

**Comment by jarena3** [comment]
I'm going to send this one to the wontfix pile because
- it **is** just kind of a cosmetics issue (and even then sort of arguable)
- I hesitate to change the synergy text to reference another synergy. I just think that'd be kind of awkward.

Having a redundant synergy is something I think I'm generally okay with, especially because there aren't a ton of cases like this.
