### ISSUE TITLE
[BUG] Use of Exposed "condition" in compedium/references

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1748]
<strong>Submitted At: </strong> 10/31/2021 3:11:56<br><br><strong>Source: </strong> LANCER Core Book<br><br><strong>Incorrect Text/Data: </strong><br> 3+ - Your mech immediately suffers from the exposed condition until it takes action to remove it. <br><br><strong>Correct Text/Data: </strong><br> 3+ STRESS: Your mech becomes EXPOSED.<br>

**Comment by lenaleciel** [comment]
The overheating table was corrected to no longer inaccurately refer to the exposed status as a condition, but this also changed the 2 stress result of a 1 to a free action rather than a full action. This was a known typo in the book that was corrected but then mistakenly rolled back at the time of the book's printing. 

Further information can be found here. https://github.com/AshleyMoni/Lancer-Community-Edition/issues/907 , and the lancer unofficial faq as a note linking to word of Tom about this on the server here. https://lancer-faq.netlify.app/#bf060b

**Comment by msprijatelj** [comment]
Reopening in light of the `free/full` typo.
