### ISSUE TITLE
[BUG] Last Argument of Kings only useable once per mission

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1755]
<strong>Submitted At: </strong> 11/3/2021 8:42:32<br><br><strong>Issue: </strong><br> If you take Hacker III, you gain the full tech attack 'Last Argument of Kings'. COMP/CON only allows you to use this once per mission, as though its a core power or limited use. Core rules says only 'you gain the option'. Nothing is listed as limited use or once per mission/scene/etc.<br><br><strong>Massif Reference: </strong> Lancer Core Rulebook, page 96.<br>

**Comment by msprijatelj** [comment]
This may be a result of the changes from #1744.  I'm noticing this happens for all Full Tech actions, e.g. Law of Blades options and Markerlight.  I am also noticing that Full Tech actions do not grey out when quick/full actions have been performed on a given turn.  I believe this is an issue on CompCon's end rather than a lancer-data issue.
