### ISSUE TITLE
[FEATURE] Reserves for additional pilot weapons and gear

### ISSUE THREAD

**Issue by ndestler** [massif-press/compcon#1810]
Currently, there is no way to add additional pilot weapons or gear to a character in Compcon. This makes it difficult to keep track of pilot-level narrative items, as well as certain rewards and some forms of homebrew content.

To solve that, I would like to see reserve options added for additional pilot weapons or gear.

Alternatively, there could be some way (reserve or otherwise) to add additional pilot gear or weapon _slots_. That would also solve the problem, although my intuition is that that would require a more significant change to the code.

Thank you for your consideration.

**Comment by msprijatelj** [comment]
There is currently the Extended Harness reserve that grants 1 extra Pilot Weapon and 2 extra pieces of Pilot Gear to a pilot that has the reserve.  It does not appear to stack, however.

Otherwise, for a workaround on the current version of CompCon (v2.3.8), the name of the reserve could always be recorded in the Player Notes section of the Dossier tab. Unsure of prioritization of a more intense form of this feature request.

**Comment by msprijatelj** [comment]
Closing in favor of #1810
