### ISSUE TITLE
[BUG] Mobile Sign-In issue (case sensitivity)

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1850]
<strong>Submitted At: </strong> 2/7/2022 16:14:26<br><br><strong>Browser: </strong> Safari<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> The email form is case senstitive<br><br><strong>Reproduction Steps:<br> </strong> When i sign in with a capital first letter, it does not let me sign in<br><br><strong>Expected Result:<br> </strong> I should be able to sign in regardless of the case of my email<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
@jarena3 What would be the fallout of making usernames case-insensitive? I'm imagining that users that accidentally created two different accounts with the same Email but different case-sensitivity would be locked out of one of their accounts as a result.  What strategies could be employed to transition to a case-insensitive system with minimal data loss?

**Comment by msprijatelj** [comment]
Maybe one thing we could try is a half-change, in a way? We make it so that all *new* compcon accounts are shifted to lowercase, but legacy accounts with case sensitivity can still be accessed? And we perform two login requests if necessary, one with case sensitivity and one without? Something like this (pardon the Python syntax, I've been coding Python lately):
```python
try:
    login(username, password)
except:
    login(username.lower(), password)
```
