### ISSUE TITLE
[BUG] "Deployable" Misunderstandings

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1854]
<strong>Submitted At: </strong> 2/11/2022 19:59:42<br><br><strong>Issue: </strong><br> Many objects that can be placed on the map are represented using the same logic as Deployables, and are labeled as such in Comp/Con outside of the relevant tagged areas. However, things like Mines, Drones, and the Slag from the Slag Cannon aren't capital D Deployable Tagged Deployables. This leads to some confusion as Deployables are a specific tagged thing in Lancer that have rules specific to them, and the things that aren't Deployables shouldn't be described as DEPLOYABLE even if they are in fact "things that are able to be deployed."<br><br><strong>Massif Reference: </strong> <br>

**Comment by lenaleciel** [comment]
This comes up in things like #1635, for example. The easiest fix would probably just be "Have the general data class labeled Deployable be named something else, even if that's not a game term defined in Lancer, because using DEPLOYABLE in the top right of things that do not in fact count as Deployables can cause some issues.
![image](https://user-images.githubusercontent.com/49732719/153692050-28d9662b-2805-4724-9dbf-03ddb28195de.png)
This system for example, doesn't have the Deployable tag, so it doesn't interact with things that interact with Deployables, but there's the word DEPLOYABLE right there, which I can't really fault people for getting confused by.

**Comment by jarena3** [comment]
Tracked in #2228
