### ISSUE TITLE
[BUG] Missing Pilot Causes Error Reports

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1870]
<strong>Submitted At: </strong> 2/28/2022 16:34:56<br><br><strong>Browser: </strong> Opera<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> While clearing out some of my speculative or duplicate pilots, I tried to delete one of them before getting the error message "Cannot read properties of undefined (reading 'Portrait')". When refreshing the page, the pilot seemed to disappear, so I assumed it was just a weird thing that happened sometimes when deleting pilots. However, whenever I open my pilot list, it displays this error message - and the folders seem to show an extra pilot.<br><br><strong>Reproduction Steps:<br> </strong> -Create or choose a pilot.
-Give that pilot a custom portrait.
-Duplicate that pilot.
-Delete that pilot.
-If you're unlucky, the pilot won't delete, showing an error message whenever you reload.<br><br><strong>Expected Result:<br> </strong> I expected my pilot to be cleanly deleted, not showing any error messages.<br><br><strong>Additional Context:<br> </strong> This may have to do with the fact that they had custom portraits? Among the files I deleted, two of the missing files had portraits - which relate to the two error messages I'm seeing.<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read properties of undefined (reading 'Portrait')
    at a.ka (https://compcon.app/app.bundle.js:343:228371)
    at a.t._render (https://compcon.app/app.bundle.js:22:35296)
    at a.i (https://compcon.app/app.bundle.js:22:64441)
    at un.get (https://compcon.app/app.bundle.js:22:26610)
    at new un (https://compcon.app/app.bundle.js:22:26528)
    at t (https://compcon.app/app.bundle.js:22:64455)
    at a.kn.$mount (https://compcon.app/app.bundle.js:22:64602)
    at init (https://compcon.app/app.bundle.js:22:19337)
    at https://compcon.app/app.bundle.js:22:52509
    at d (https://compcon.app/app.bundle.js:22:52786)```<br>

**Comment by msprijatelj** [comment]
This has been a recurring issue since the pilot roster group rework I did a few months back. Given how it’s still affecting users, I think it may be worthwhile to revisit how we populate the roster. 

Errors like this seem to happen when there’s a mismatch between the IDs in the `pilot_groups.json` and the actual pilots, so either we should prevent those mismatches from occurring or (preferred) we disregard the IDs in `pilot_groups` altogether, use the pilots’ `SortIndex` to determine order, and generate the draggable roster object from the combination of the two (instead of reading it directly from `pilot_groups`.

**Comment by jarena3** [comment]
Fixed in 2.3
