### ISSUE TITLE
[BUG] Systems changes not persisted between page loads

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1989]
<strong>Submitted At: </strong> 5/1/2022 13:56:45<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When making changes to a mech loadout's systems, the changes (such as adding, editing, or removing systems) are not persisted after reloading the page. The systems revert back to their previous state. Navigating between pages everything works as expected, it's only after a refresh (F5) that the changes are discarded. I was only getting this behavior when not logged in.<br><br><strong>Reproduction Steps:<br> </strong> Make sure you aren't logged in.
Select a mech and view its loadout (I only had a single loadout in my scenario)
Delete one of its systems (or add a new one, I saw the same behavior either way)
Reload the page (F5)
The deleted system is back

Sometimes, the first edit seemed to stick, but subsequent changes are not saved.<br><br><strong>Expected Result:<br> </strong> Edits to a loadouts system should be persisted between page loads.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Can confirm that I can get the first edit to stick, but not subsequent changes.  This occurs with both weapons and systems when logged out.

**Comment by msprijatelj** [comment]
Delved deeper into this one. This issue appears to be due to a combination of the lack of SaveController usage at the Loadout and Mounts level AND the fact that dirty mechs aren’t included in the delta save.  I‘ve started on a fix that pulls the parent into the Loadouts/Mounts, adds a Parent to ISavableObjects, and bubbles up “IsDirty” (have to figure out if I should only bubble up “true” or bubble up both “True” and “False”).
