### ISSUE TITLE
[FEATURE] Generalized Mount Bonuses

### ISSUE THREAD

**Issue by msprijatelj** [massif-press/compcon#1992]
**Is your feature request related to a problem? Please describe.**
A common homebrew issue is wanted to modify a mech’s mounts with a bonus, but COMP/CON currently hardcodes the mount-affecting core bonuses into the website itself. With the potential of Dustgrave’s Superheavy mount core bonus on the horizon, it may be worthwhile to revisit how COMP/CON handles mount-affecting bonuses. 

**Describe the solution you'd like**
A programmatic approach to add new mounts and replace mounts when a “mount” bonus is detected on a mech’s pilot. E.g. a “flex” “replace” bonus would allow the user to replace one mount with a flex mount, a “main” “add” “integrated” bonus would add a main mount that is otherwise treated like the core integrated weapon, and “aux/aux” “add” “max 3” would simply add an aux/aux mount if the frame has less than 3 mounts already. 

**Describe alternatives you've considered**
Dustgrave’s Superheavy core bonus could be hardcoded like the rest of the core lancer core bonuses. 

**Additional context**
Dustgrave’s current iteration seems to lock up all mounts except one when a mech uses a Superheavy weapon that it usually is unable to use. This could certainly change, but it could be important to keep in mind for this feature.

**Comment by msprijatelj** [comment]
As of Dustgrave 2.6, the superheavy core bonus simply creates a new exclusive “Superheavy” Mount if a mech has fewer than 3 mounted and requires a Heavy Mount to be used as bracing if present.

**Comment by Melted-Gallium** [comment]
could you add me to this feature next? gonna be tackling this for a bit, and have been before personal stuff made me pause for a bit

**Comment by Melted-Gallium** [comment]
actually, a question on this one. implementing these changes would mean that the old way of having the bonuses are separate fields in the mech loadout class. should  I try and make it backwards compatible, so that if I was loading a character with the old version it would translate to the new? following off of that, I may not be sure how to ensure that old characters that were loaded (saved in the system) wouldn't break when updating. any suggestions on that front would be extremely helpful.

**Comment by msprijatelj** [comment]
Ideally these would be backwards compatible, though I’ll admit I’m not sure how easy it would be to translate this to practice. The existence of a free-standing Dustgrave LCP means that we wouldn’t just be able to smoothly ship the change alongside a Lancer-data change, so some kind of backwards compatibility will likely be necessary.

**Comment by msprijatelj** [comment]
Actually, not that I think of it, it should be possible to just keep the hardcoding in for Lancer data and Dustgrave for now? And then just accommodate homebrew using the bonus mounts. Then the matter of bringing official Lancer data up to speed will be a separate issue.

**Comment by Melted-Gallium** [comment]
That should be doable tbh, I’ll see what I can fo

**Comment by Melted-Gallium** [comment]
I think the problem with that approach as it stands right now, the code elsewhere knows if it has the core bonuses that grant the mount changes and then just asks for the data that those mounts hold. As I was thinking of implementing it, There was going to be an array of mounts that would be added on to and removed from as needed. However, if a new mech was created then the mech controller wouldn't necessarily know what bonus slots to add on. in addition, as far as I'm aware, there isn't a bonus controller class or similar elsewhere, especially since the bonus class is used on everything from core bonuses, to reserves, to the bonus abilities the systems and weapons give. I'm not having much luck implementing it in this way, any suggestions for how I might be able to rework this idea?

**Comment by Melted-Gallium** [comment]
scratch that, I found the feature controller, and will need some time to think

**Comment by Melted-Gallium** [comment]
alright. I think I've got it working for 3/5 possible locations that the given bonus (chose the name "mount-modification" for later reference) the remaining 2 are ones that I'm hesitant to implement, partially from a game balance perspective, and partially from a sense perspective: this would be on mech systems/weapons and pilot gear, weapons, and armor. (grouping them this way due to the controller each set has in common). in addition, of the two, pilot gear would be harder to implement due to it's separation from the getters/setters of the loadout itself. (if implemented, I can either tell the loadout about its controller, or redo all implementations in the VUE sections (would be difficult) and have the getters/setters be in the controller that then call the ones in the base loadout class) thoughts on this problem in general?

**Comment by msprijatelj** [comment]
Closed by #2300
