### ISSUE TITLE
[BUG] LUCIFER-Class NHP Missing 

### ISSUE THREAD

**Issue by ihave3settings** [massif-press/compcon#2175]
Not available as an addable NHP.
<img width="971" alt="Screenshot 2023-01-20 015152" src="https://user-images.githubusercontent.com/23565067/213635454-8fdd138a-37b4-4b0e-bb73-f2051e1698f9.png">
<img width="971" alt="Screenshot 2023-01-20 015248" src="https://user-images.githubusercontent.com/23565067/213635462-86160907-454d-450c-b76b-5f9017ecd563.png">

Tried making a standard Tokugawa, same issue.
Other members of game also checked, and same issue.

**Comment by ihave3settings** [comment]
Upon further inspection, the Tokugawa frame is also missing

**Comment by msprijatelj** [comment]
@ihave3settings I can’t seem to reproduce this on CompCon v2.3.11, Firefox browser. Can you please list your Operating System, Browser, and CompCon version, as well as any relevant steps to reproduce? In addition, could you please send a screenshot of all your installed LCPs?

**Comment by ihave3settings** [comment]
Not sure what happened but it fixed?

**Comment by msprijatelj** [comment]
Okay, glad to see it fixed, though I'm frankly baffled it happened in the first place. My best guess is that the core data stopped loading before Tokugawa finished (since Tokugawa is the last mech license in the list) but I feel like that's a weak explanation.  In any case, glad Tokugawa is showing up again.
