### ISSUE TITLE
[FEATURE] Mech designs without pilots

### ISSUE THREAD

**Issue by ryderd9323** [massif-press/compcon#2242]
**Is your feature request related to a problem? Please describe.**
Would like to be able to make and save mech designs independent of pilots. I have lots of ideas for mechs that I don't necessarily want to tie to a particular pilot, but right now you can only make a mech if through an associated pilot.

**Comment by jarena3** [comment]
This has been a fairly common request since the early days of the app, but it's not something I'm ever going to implement. C/C is supposed to be a tool for Lancer games and characters, and in Lancer characters and their mechs are just too interconnected to extract in a way that doesn't add a bunch of stuff that's unsupported in the actual playing of Lancer games. Mechs outside of characters just don't make a ton of sense, even in sort of white-room theory crafting.
I understand there are users who like or use C/C for reasons outside of strictly managing Lancer characters etc. but I've got to draw the line sometimes and this is one of those times.
