### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Cullen98** [massif-press/compcon#2277]
**Describe the bug**
Every time i log in my data has been completely erased

**To Reproduce**
1. Go to page
2. Click on login
3. See blighted wasteland where my mechs used to be

**Expected behavior**
A website with
echs

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: latest ios
 - Browser: Safari
 - Version: latest

**Additional context**

**Comment by msprijatelj** [comment]
Are you saving your mechs to the cloud with "Smart Sync All" or "Overwrite Cloud"? Because you'll need to manually save them to the cloud at this point in time.

Additionally, in case this is a cache-clearing issue, please make sure you aren't clearing your browser cache for CompCon (or whitelist the site for any browser extensions that do so).
