### ISSUE TITLE
[BUG] Can't Reset Password 

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2452]
<strong>Submitted At: </strong> 5/2/2024 22:20:00<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> I can't Reset my password for my account. Gives me the ERROR:   Unable to change password: Username/client id combination not found. message (and no I can't use my original login device as it doesn't exist anymore)<br><br><strong>Reproduction Steps:<br> </strong> try to reset my password on any device other then my old phone that I first logged in on. (this phone is broken and gone)<br><br><strong>Expected Result:<br> </strong> I'd really just like to be able to reset my password from any of my other devices<br><br><strong>Additional Context:<br> </strong> Sorry I'm really frustrated I can't remember my password thought I had it written down (phone broke now can't login on anything else)<br><br><br><strong>Stack Trace: </strong>  ERROR:   Unable to change password: Username/client id combination not found.<br>

**Comment by msprijatelj** [comment]
I would say to try changing the capitalization of your email, detailed here: https://github.com/massif-press/compcon/wiki/Troubleshooting-Issues#compcon-says-my-account-doesnt-exist

Because there's no name provided for follow-up, there's not much else we can do other than hope this solves the issue. Please feel free to make a Github account to follow up on this issue.
