### ISSUE TITLE
[BUG] Verification

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2453]
<strong>Submitted At: </strong> 5/3/2024 2:56:44<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> I tried to make an account, accidentally closed the verification page for the email, now the page is gone and I can't enter the code<br><br><strong>Reproduction Steps:<br> </strong> make a new account, get the email code, then close the page with the code
<br><br><strong>Expected Result:<br> </strong> well i wish i had a link<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Hello! This is a common enough issue, so I made a Troubleshooting entry today to answer this question: https://github.com/massif-press/compcon/wiki/Troubleshooting-Issues#how-do-i-verify-my-compcon-account

Otherwise, without additional information, we won't be able to follow up with you. Hopefully this helps you with your issue; if you continue to have problems, feel free to make a Github account to reopen this issue.
