### ISSUE TITLE
Make mod installation easier to find

### ISSUE THREAD

**Issue by aritsune** [massif-press/compcon#285]
We've gotten several false positive reports of people who think their weapon mods are bugged since they don't show up on the add system dialog. I propose we make the way they're installed clearer by both making the wrench icon more visible (maybe "Install Mod" text?) & by also adding a warning to the top of the add system dialog if there's any mods the player can install.

In the future we can also look into adding an alternate way to install mods via the system table, but that's a little unorthodox and would take more doing than these two solutions.

**Comment by CommanderTso** [comment]
Looking at this, a couple ideas come to mind:
- I'd like to put the text, "Mods" next to the wrench, inline.  Short and sweet, and true since you can both add and remove mods from there.
- For highlighting if there are mods available, what if the wrench button and text were under a blue background if there are available mods?  Possibly also pairing that with changing the change-equipped button to blue?

Tagging @jarena3 to get his input, since he cares about UIs and colors. :)

**Comment by jarena3** [comment]
that seems good -- keep the icon as-is unless there are mods available but not applied, in which case change the icon like you described.
I like it.
