### ISSUE TITLE
[FEATURE] Talent synergy highlights

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#506]
**Is your feature request related to a problem? Please describe.**
C/C doesn't reason about the actual content of talents, for the most part. If a user has eg. talents that modify a weapon, they must remember to apply those changes whenever they use the weapon.

**Describe the solution you'd like**
Talent ranks and items should contain data that allows us to match effects with items. For example: Vanguard's Rank I talent "Handshake Etiquette" grants +1 accuracy to CQB weapons when they're attacking in range 3. 
If a pilot has Vanguard I, all equipped CQB weapons should display a "talent" icon that, on hover, pops a tooltip with the talent effect.

**Additional context**
This, too, should be a broadly generalized solution to tie talents to things.

**Comment by Qwertronix** [comment]
One potential solution that is _relatively_ easy code-wise but pushes the burden onto data devs and homebrew devs:

Use a query/selector scheme, potentially something similar to REST or CRUD querying conventions to leverage existing ecosystem code and patterns, to apply a corresponding hint content payload to that object. 

Some requirements and caveats: 

- [ ] slots in cards where the payload could end up, for rendering (idea: since tags seem to also be able to end up almost anywhere that Talent hints might, perhaps there's a UX synergy to be exploited here?)
- [ ] basic structure for the talent data itself: array of hint objects, each containing a query/selector and a payload
- [ ] query structure & parsing, which could have a target item type and a set of conditions to be matched on that item
- [ ] list of target item types
- [ ] parsing the query and converting it into runtime -- is it a fixed set of possible things to check, as with a select-case? something more flexible powered by javascript treating objects the same as hashtables for property access at runtime? how are breaking changes handled, flagged and communicated? 
- [ ] executing the query on the items, which could imply either messier internal state tracking if the items themselves are modified, or having these queries passed around through a lot of components during their render cycles

**Comment by mindbane** [comment]
My suggestion based upon our discord discussion

modify the talent configuration JSON to contain a render condition section such as

```
{
    Name: "Handshake Etiquette"
    Render: {
                Location: Weapon //defines that this talent should show up in a weapon description
                Conditions: { Type: "Tag", value: "CQB", scope: "Weapon", state: true }
            }
    Perk: <Body of Perk Here>
    ...
}
```

Then have the talent loader process the render conditions and feed them into the appropriate listener for a part of the site being rendered. in this case when a weapon is rendered. Then the evaluator can check to see if the conditions are all met in this case that the weapon has the tag CQB and if so render the perk body.

You can easily extend this to handle things like CQB = true but loading = false or check the state of other items like pilot hull skill > 2. etc.

**Comment by jarena3** [comment]
the first pass of this is going into dev now. Currently, only `weapon` and `system` are valid locations (both on the loadout panel), but as I rework active mode I'll be adding more sites for synergy notifications and explicit abilities gained by talents
