### ISSUE TITLE
[BUG] NPC Template Systems not Appearing

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#682]
<strong>Submitted At: </strong>3/6/2020 18:10:37
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When I go to NPC Templates through Compendium and click on their features, only a blank box appears. 
<strong>To Reproduce: </strong>
Go to NPC Templates through Compendium.
<strong>Expected behavior: </strong>
The descriptions of the features should appear.
<strong>Additional context: </strong>
Just updated to 2.0.21, tried hard resetting browser but still have the problem.
<strong>Contact Info: </strong>

**Comment by Eranziel** [comment]
Did some digging. The cause is that the NPC features use the `CCItemEffectPanel` component, which has been updated in 2.0.11. The NPC feature effects still use `string` instead of generating `ItemEffect` arrays.

@jarena3 I think the long-term goal would be to update all the NPC features to align with the new data format. Short-term is probably to treat all NPC feature effects as `GenericEffect`?

**Comment by jarena3** [comment]
my plan was to start to integrate NPC Feature effects into the new scheme but I've run out of time. I'll get out a quick workaround hack then make a note to get to it later
