### ISSUE TITLE
[BUG] NPC classes can't be sorted in Compendium

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#840]
<strong>Submitted At: </strong>5/8/2020 21:16:35
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When looking at the list of NPC classes in the Compendium, the tabs to sort NPCs by any categories other than Name and Role don't work.
<strong>To Reproduce: </strong>
Go to Compendium, click NPC classes, and try to sort the list by HP, Armour, Speed etc - the list will not sort itself.
<strong>Expected behavior: </strong>
Clicking on one of the headers should sort the list by that category - ie, ascending by heat cap, descending by speed, etc
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by msprijatelj** [comment]
I took a look at this issue, did some searching, and found this StackOverflow question that resembled the issue: https://stackoverflow.com/questions/55231188/sort-vuetify-table-by-displayed-text-not-model

I admit I'm relatively new to Vue, but my amateur opinion is that because the NpcClasses `v-data-table` item templates are using an evaluated function (e.g. `item.Stats.HP(tier)`) instead of a pre-computed value, the `v-data-table` sorts by that function instead of the final computed value.  The solution to the StackOverflow question suggested using Vue's `computed` property for such pre-computation.

I hope this may prove helpful for a fix! If not, I look forward to learning from the actual solution. 😅

**Comment by msprijatelj** [comment]
I took a look at this issue, and while I am admittedly new to Vue + Typescript, I believe the issue is that the tier-related stats should be pre-computed outside of the HTML template and _then_ called by the template.  However, I'm not sure of the best place to perform that computation.  My initial instinct would be to introduce stat "setter" functions to the NpcClassStats class that take the `tier` as input and compute/store the appropriate stats for the tier, then use the "getter" functions to call the stats.  That said, I'd be happy to hear the opinion of someone better-versed in Vue.

**Comment by jarena3** [comment]
@msprijatelj without looking this is almost certainly the case -- I was holding off until I take my NPC/GM pass, but if you're interested in it feel free and I'll merge it in in the meantime
