### ISSUE TITLE
[BUG] Catapract Charge Trait doesn't have Recharge toggle in Mission Runner

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#942]
<strong>Submitted At: </strong>7/3/2020 23:41:57
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When running an encounter and looking over a Cataphract's sheet, the Charge trait doesn't have a switch to toggle the Charge/Recharge
<strong>To Reproduce: </strong>
Create a Cataphract NPC, give it the Charge optional trait, put it in an encounter, put that encounter in a mission, run the mission and the encounter, then view the Cataphract
<strong>Expected behavior: </strong>
The Charge text block should have a switch to indicate whether the trait is charged or not
<strong>Additional context: </strong>
I think I've seen this for other traits/systems of other NPCs too, not sure I noticed a pattern yet
<strong>Contact Info: </strong>
VertigoCharades (he/him)#1590
<strong>Stack Trace: </strong>

**Comment by Mischala** [comment]
Looking into this.
Think I found the problem.

On the same Mech, "IMPALE" is a recharging System, its card does have the Recharging toggle.
looking at the code for Charge, Charge is classed as a Trait, not a System.
Traits do not have the concept of Recharging.  even though the tag can be applied.

The Switch doesn't get added because traits aren't checked to see if they have the isRecharging flag

The solution is probably to apply the same IsRecharging logic to Traits.

**Comment by Mischala** [comment]
Got a PR in for this.
#943 

![brave_2020-07-05_14-13-29](https://user-images.githubusercontent.com/2610510/86524068-e6e9b000-bec9-11ea-9eb9-5eee70961691.png)
