### ISSUE TITLE
[BUG] NHPs filtering incorrectly

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#996]
<strong>Submitted At: </strong>7/20/2020 4:55:43
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When filtering by the AI "type," the Didymos and Osiris NHPs do not show up in the Compendium. They do show up when filtering by the AI *tag.*
<strong>To Reproduce: </strong>
Open Compendium. Select "Systems." Select filter button in the upper right. Open "System Type" dropdown menu and select "AI."
<strong>Expected behavior: </strong>
I expected all of the AI systems to appear when filtering by the AI type.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Discord: Veritas#1272
<strong>Stack Trace: </strong>

**Comment by RobotKernel** [comment]
Quick look at Didymos and Osiris reveals that their type in lancer-data and long-rim-data are "type": "Tech" instead of "type": "AI".

This isn't the only case of "name" tag != "name" type. Stasis barrier has the shield tag but is a deployable system type.

I wonder what the goal here is with having system types (at least user facing). Because right now filtering by system type Tech will give you everything that has the "Tech" system type but it isn't an overview of all system that give or affect tech actions. This view misses Sisyphus for example. But if you select the quick & full tech actions tags you miss systems like scanner swarm, giving the user no way to efficiently view every system that is Tech related.
